name: "Update latest version to the release version."
on:
  push:
    paths:
      - 'release-versions/*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name "Fetch version hash"
        run: |
          export version=$(cat release-requests/osu-latest.txt)
          export hash=$(sh auto-update/get-hash.sh)
      - name "Apply patch"
        run: |
          sh auto-update/gen-patch.sh "$hash"
      - name "Push version"
        git config --global user.name 'Hashelq'
        git config --global user.email 'hashelq@users.noreply.github.com'
        git add bypass-tamper-detection.patch
        git commit -m "Update to version $version"
        git push

