name: "Update to the release"
on:
  workflow_dispatch:
  push:
    paths:
      - 'release-versions/*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
      - name: "Fetch version hash"
        run: |
          echo version=$(cat release-requests/osu-latest.txt) >> "$GITHUB_ENV"
          echo hash=$(sh auto-update/get-hash.sh) >> "$GITHUB_ENV"
      - name: "Apply patch"
        run: 'bash auto-update/gen-patch.sh "$hash"'
      - name: "Push version"
        run: |
          git config --global user.name 'Hashelq'
          git config --global user.email 'hashelq@users.noreply.github.com'
          git add bypass-tamper-detection.patch
          git commit -m "Update to version $version"
          git push

